module SamplePodcasts
PODCASTS = [
[ "Politics", "The latest podcast feed searching 'Politics' on SermonAudio.com.", "Politics - SermonAudio.com", "http://is1.mzstatic.com/image/thumb/Music62/v4/28/a0/0f/28a00fee-e9bf-c176-fc70-8d7453dc92d0/source/600x600bb.jpg", "Christianity"],
[ "Politics", "Our weekly podcast on political matters", "Politics", "http://is5.mzstatic.com/image/thumb/Music4/v4/83/e7/ec/83e7ec84-fdb8-ed27-ef0a-fdd1248c2c4d/source/600x600bb.jpg", "News & Politics"],
[ "NPR", "The NPR Politics Podcast is where NPR's political reporters talk to you like they talk to each other. With weekly roundups and quick takes on news of the day, you don't have to keep up with politics to know what's happening. You just have to keep up with us.", "NPR Politics Podcast", "http://is5.mzstatic.com/image/thumb/Music122/v4/78/cf/f3/78cff347-3d72-de61-d3f7-dc2cd785e462/source/600x600bb.jpg", "News & Politics"],
[ "FiveThirtyEight - Nate Silver, Jody Avirgan, Clare Malone, Harry Enten", "Nate Silver and the FiveThirtyEight team cover the latest in politics, tracking the issues and game-changers every week.", "FiveThirtyEight Politics", "http://is2.mzstatic.com/image/thumb/Music62/v4/c2/fc/d2/c2fcd2dd-d8e2-6b53-36b1-bdfe946e5568/source/600x600bb.jpg", "News & Politics"],
[ "WNYC Studios and The New Yorker", "A weekly discussion about politics, hosted by The New Yorker's executive editor, Dorothy Wickenden.", "The New Yorker: Politics and More", "http://is1.mzstatic.com/image/thumb/Music71/v4/b9/ae/b6/b9aeb685-2b75-30ff-7c01-4c579e15b2bc/source/600x600bb.jpg", "News & Politics"],
[ "HuffPost Politics", "An inside-the-beltway show that's truly for beltway outsiders. Each week the HuffPost Politics team offers an entertaining alternative to the Sunday shows you've stopped watching. Along with their outside the beltway guests, join Arthur Delaney, Zach Carter, and Jason Linkins as they analyze the news of the week and explain why it should matter to you.", "So That Happened", "http://is5.mzstatic.com/image/thumb/Music71/v4/d5/6e/ab/d56eab4e-4cec-ff85-3634-22a27c830bb9/source/600x600bb.jpg", "News & Politics"],
[ "Bruce Carlson", "Today's political debates, particularly on cable news, talk radio and blog comments can be limiting.  In this podcast, Bruce Carlson applies as much history as possible to the politics of today.  ", "My History Can Beat Up Your Politics", "http://is2.mzstatic.com/image/thumb/Music4/v4/96/15/1d/96151df4-108b-f68a-7430-5a9737a391c2/source/600x600bb.jpg", "News & Politics"],
[ "TEDTalks", "Seeing the world beyond news headlines: politicians, journalists and researchers share their insights onstage at the TED conference, TEDx events and partner events around the world. You can also download these and many other videos free on TED.com, with an interactive English transcript and subtitles in up to 80 languages. TED is a nonprofit devoted to Ideas Worth Spreading. ", "TEDTalks News and Politics", "http://is4.mzstatic.com/image/thumb/Music4/v4/a8/42/8f/a8428f99-109a-3500-5dd7-eaee704657fa/source/600x600bb.jpg", "News & Politics"],
[ "The Weekly Standard", "The Weekly Standard Podcast delivers unique analysis of the events shaping the news and the world today - from a conservative perspective. Host Michael Graham leads an all-star roster of the best conservative minds including: Bill Kristol, Fred Barnes, Stephen F. Hayes, Andy Ferguson, Jonathan Last, Dan Halper and many more. Learn more about The Weekly Standard  and our weekly magazine at WeeklyStandard.com", "Weekly Standard Podcast - Your source for conservative analysis of the news shaping US politics and world events", "http://is5.mzstatic.com/image/thumb/Music62/v4/64/60/d4/6460d4ce-76d1-699a-bce1-bbd4753d6785/source/600x600bb.jpg", "News & Politics"],
[ "Julie & Brandy", "Join Julie Goldman (the gay) and Brandy Howard (the dumbass) as they dissect this week's political news. The podcast with lots of feelings, but no actual facts.  New episodes every Tuesday!", "Dumb, Gay Politics", "http://is3.mzstatic.com/image/thumb/Music62/v4/bd/c5/af/bdc5af2d-3de8-8bf2-3d39-ead9bc8527d9/source/600x600bb.jpg", "Comedy"],
[ "Capitol Steps", "The Capitol Steps bring their political musical satire to the air, now in two hour-long shows.  Tune in on the Fourth of July and New Year's Eve.Visit our website at www.capsteps.com for weekly songs and to purchase albums. We put the MOCK in Democracy!", "Capitol Steps: Politics Takes a Holiday", "http://is1.mzstatic.com/image/thumb/Music62/v4/f6/96/df/f696df9c-2dc2-951b-96b2-5bca9894c022/source/600x600bb.jpg", "Comedy"],
[ "KCRW.com", "Sometimes a panel discussion about current controversies in the cultural world, other times an in-depth interview with an author or leading figures in media the arts entertainment or politics, 'The Politics of Culture' examines the intersection where the world of politics and culture meet and sometimes collide.", "KCRW's Politics of Culture", "http://is4.mzstatic.com/image/thumb/Music/v4/7e/0c/9b/7e0c9bab-1354-f276-0a9f-a482827e9acf/source/600x600bb.jpg", "Design"],
[ "Pantsuit Politics", "A podcast where a woman from the right and a woman from the left accessorize the news with a fresh perspective. Sarah Stewart Holland and Beth Silvers bring a nuanced perspective to discussions about politics and current events.", "Pantsuit Politics Podcast", "http://is3.mzstatic.com/image/thumb/Music71/v4/03/b6/55/03b65519-113e-8358-c5e1-30f157599543/source/600x600bb.jpg", "News & Politics"],
[ "Randy Newberg: Hunter, Host of Fresh Tracks TV, Speaker, and Hunting Activist", "Hunt Talk Radio, Randy Newberg Unfiltered is a podcast covering hunting politics, public lands, and conservation topics; even a few things you didn’t need to know.  The best hunters you’ve never heard of join Randy to answer questions from the Hunt Talk web forum, share ideas, reveal tactics, and give perspectives unique to public land hunting.", "Hunt Talk Radio, Randy Newberg Unfiltered | Hunting | Conservation | Politics | Tactics", "http://is1.mzstatic.com/image/thumb/Music62/v4/5b/97/a8/5b97a8d4-dcf9-5679-3551-426fb0922677/source/600x600bb.jpg", "Outdoor"],
[ "Michael Baranowski and Jay Carson", "It&#039;s about politics. It&#039;s about ideas. It&#039;s about half an hour.", "The Politics Guys", "http://is2.mzstatic.com/image/thumb/Music62/v4/25/06/b9/2506b935-3125-d16d-4024-6c39cff93be7/source/600x600bb.jpg", "National"],
[ "theguardian.com", "If you’re keen to keep abreast of UK and international politics then our Politics Weekly podcast is for you. The Guardian’s politics team unwind the political spin and delve into the key issues that drives the people in power. UK politics is the focus but the team also look at the big global political stories each week. Panellists include Guardian writers such as  Rowena Mason,  Gary Younge,  Polly Toynbee,  Michael White and  Rafael Behr and we regularly have guests from all side of the political spectrum", "The Guardian UK: Politics Weekly", "http://is5.mzstatic.com/image/thumb/Music62/v4/67/04/54/67045450-2ff2-4f3f-f5b7-3cf284ca25b2/source/600x600bb.jpg", "News & Politics"],
[ "ABC News", "Headliner interviews and in-depth looks at the people and events shaping U.S. politics. Hosted by ABC News' Chief White House Correspondent Jonathan Karl, Political Director Rick Klein and Chief Political Analyst Matthew Dowd.", "Powerhouse Politics", "http://is2.mzstatic.com/image/thumb/Music19/v4/97/d1/d3/97d1d3f3-45b2-77ab-6b35-9ab38fe4dcf0/source/600x600bb.jpg", "News & Politics"],
[ "Justin Robert Young", "Justin Robert Young announces his intention to dissect the run for the White House. Just think, while you been getting down and out about the liars and the dirty dirty cheats of the world you could have been getting down to this sick beat.", "Politics Politics Politics", "http://is3.mzstatic.com/image/thumb/Music71/v4/63/16/15/63161514-c066-2945-750b-51bed26f70f7/source/600x600bb.jpg", "National"],
[ "Slate Magazine/Panoply", "Readings and discussions featuring today's best authors, recorded live at Washington DC's famous Politics & Prose bookstore and presented by Slate.com. Part of the Panoply Network.", "Slate's Live at Politics and Prose", "http://is1.mzstatic.com/image/thumb/Music71/v4/6d/78/11/6d7811bd-5847-da66-8e55-e4397b8448bc/source/600x600bb.jpg", "Literature"],
[ "Marketplace", "The economy & politics – from waaaaay outside the beltway. Marketplace looks at what matters most to Americans, and why the frame of insiders vs. outsiders says more than the stale divisions of left vs. right and big government vs. small. From American Public Media. Visit Marketplace.org for more, or find us on Twitter, we're @marketplace.", "Politics Inside Out from Marketplace", "http://is5.mzstatic.com/image/thumb/Music62/v4/2b/00/6e/2b006ede-5b3b-c469-52c9-ebe53feddf16/source/600x600bb.jpg", "News & Politics"],
[ "Bloomberg News", "Under the leadership of Bloomberg Washington Bureau Chief Megan Murphy, veteran political TV news producers Betsy Fischer Martin and Tammy Haddad explore the tradecraft of politics with candidates, strategists and fellow journalists, including regular reporting and analysis from Bloomberg contributors.", "Masters in Politics", "http://is3.mzstatic.com/image/thumb/Music71/v4/a3/9b/0c/a39b0c91-db86-bc50-a059-2df7e042494a/source/600x600bb.jpg", "News & Politics"],
[ "Steve Patterson | Covering Philosophy, Religion, Politics, Economics, Science, Mathematics, Metaphysics, Epistemology, Logic, Truth, Christianity, Buddhism, Hinduism, Atheism, Spirituality, Language, and Cultural Criticism", "Interviews with intellectuals from across the globe. Topics include philosophy, religion, science, politics, economics, and everything else that's important to humans. Steve Patterson is a philosopher working outside of academia, and he is currently traveling the world to interview people in the pursuit of truth.", "Patterson in Pursuit: Philosophy | Politics | Religion", "http://is5.mzstatic.com/image/thumb/Music71/v4/0b/57/7e/0b577efb-aaed-0980-ffac-880ebc9a8eae/source/600x600bb.jpg", "Philosophy"],
[ "Shorenstein Center on Media, Politics and Public Policy at Harvard Kennedy School", "The Shorenstein Center Media and Politics Podcast features insight and expertise from leading voices at the intersection of media, politics and public policy. Prominent journalists, editors and academics address topics such as the media industry, campaigns and politics, foreign policy, race and gender, and technology.", "Media and Politics Podcast", "http://is4.mzstatic.com/image/thumb/Music62/v4/01/73/e6/0173e64d-80b6-e7a1-ca2d-ac9e22d7d608/source/600x600bb.jpg", "News & Politics"],
[ "Slate", "
            
                Your daily politics update, brought to you by Slate. A SpokenEdition transforms written content into human-read audio you can listen to anywhere. It's perfect for times when you can't read - while driving, at the gym, doing chores, etc. Find more at www.spokenedition.com
            
        ", "Slate Politics – Spoken Edition", "http://is3.mzstatic.com/image/thumb/Music71/v4/35/21/e3/3521e331-6ba7-1319-1035-868a64d01da7/source/600x600bb.jpg", "News & Politics"],
[ "WAMU 88.5", "Sorting political fact from fiction, and having fun while we're at it. Join us for our weekly review of the politics, policies, and personalities of the District of Columbia, Maryland and Virginia.", "The Kojo Nnamdi Show: The Politics Hour", "http://is1.mzstatic.com/image/thumb/Music62/v4/c7/b2/5b/c7b25b6f-b8d9-6425-e579-343185b9f5a8/source/600x600bb.jpg", "News & Politics"],
[ "Letters and Politics", "Letters & Politics seeks to explore the history behind today’s major global and national news stories. Hosted by Mitch Jeserich.", "KPFA - Letters and Politics", "http://is1.mzstatic.com/image/thumb/Music49/v4/d2/b4/21/d2b421ee-5d99-840e-1a00-5832b27da808/source/600x600bb.jpg", "News & Politics"],
[ "David Runciman and Catherine Carr", "Corbyn! Trump! Brexit! Politics has never been more unpredictable, more alarming or more interesting. TALKING POLITICS is the podcast that will try to make sense of it all. Each Thursday, in Cambridge, David Runciman will talk to his regular panel along with novelists, comedians, historians, philosophers - and even a few politicians - and ask them what they think is going on... Democracy is feeling the strain everywhere. What might happen next? How bad could it get? As it unfolds, TALKING POLITICS will be on it. It’s the political conversation everyone is having: please join us.", "TALKING POLITICS", "http://is5.mzstatic.com/image/thumb/Music71/v4/b7/b2/7a/b7b27a7e-0a9b-8ff7-7786-7aa40a9c6f99/source/600x600bb.jpg", "News & Politics"],
[ "The Huffington Post", "
            
                Follow American politics, keep up with the hottest political debates, and share your thoughts and opinions on the political news that matters to you.     A SpokenEdition transforms written content into human-read audio you can listen to anywhere. It's perfect for times when you can't read - while driving, at the gym, doing chores, etc. Find more at www.spokenedition.com
            
        ", "HuffPost Politics – Spoken Edition", "http://is2.mzstatic.com/image/thumb/Music71/v4/79/25/fd/7925fd60-a6eb-794e-ea6f-ab53ceb078df/source/600x600bb.jpg", "News & Politics"],
[ "PodcastOne", "Examining Politics, a weekly Washington Examiner podcast from Washington, D.C., that takes you deep inside political campaigns and Congress for a detailed look at what's happening, what's going to happen, and why.", "Examining Politics", "http://is5.mzstatic.com/image/thumb/Music62/v4/69/1e/9d/691e9d54-adb3-2baf-a8e6-2e0a566f11d2/source/600x600bb.jpg", "News & Politics"],
[ "Courtney Brown, Ph.D.", "Science Fiction and Politics, Courtney Brown, Emory University", "Science Fiction and Politics, Courtney Brown, Emory University", "http://is2.mzstatic.com/image/thumb/Music62/v4/ce/80/27/ce80272b-066b-182e-3bde-decf1e353686/source/600x600bb.jpg", "Higher Education"],
[ "John Myers", "Home of the weekly California Politics Podcast, hosted by John Myers of the Los Angeles Times.", "California Politics Podcast", "http://is3.mzstatic.com/image/thumb/Music71/v4/a9/52/3c/a9523c8f-7ae4-e6b8-0c93-dc63144f6768/source/600x600bb.jpg", "News & Politics"],
[ "Oregon Public Broadcasting", "OPB Politics Now takes a deep dive into the hottest political topics of the week. Every Friday, Host Geoff Norcross, OPB Senior Political Reporter Jeff Mapes along with other OPB reporters, editors, and special guests offer the inside scoop about candidates and issues affecting our region. They provide in-depth analysis, insight on the local political landscape and rousing conversation to satisfy the most enthusiastic political junkies as well as those who may not follow Oregon politics as closely. ", "OPB Politics Now", "http://is3.mzstatic.com/image/thumb/Music62/v4/5d/e9/30/5de9308e-5214-56b2-10de-13b5fa439a75/source/600x600bb.jpg", "News & Politics"],
[ "Karen Tate", "Named one of the Top 13 Most Influential Women in Goddess Spirituality - tune in to find out why!  Wednesday or Thursday nites, hear Dr. Rev. Karen Tate, author, speaker, and teacher, discussing global and personal issues with a broad spectrum of advocates, visionaries and forward thinkers from a Divine Feminine, Right Brain point of view.  Some call it the Feminine Consciousness or the shift away from patriarchal values.  These are issues that could raise your consciousness or save the world.  It's all the stuff Mom taught you to NEVER discuss at the dinner table - sex, religion, power and politics.  Fear Not - taste the forbidden fruit!  Rethink, reclaim and embrace the age old knowledge that's been denied us for too long.  Unlock your female tool kit and empower yourself as you learn long hidden truths from your home altar to the voting booth.  Learn what denying the feminine face of god, whether the Great She be deity, archetype or ideal, has cost humanity - particularly women!  Karen Tate's 4 published books include: Sacred Places of Goddess: 108 Destinations, Walking An Ancient Path: Rebirthing Goddess on Planet Earth, Goddess Calling - Inspirational Messages & Meditations of Sacred Feminine Liberation Thealogy and the anthology based on this show, Voices of the Sacred Feminine: Conversations to ReShape Our World.  Please like my Facebook pages for each book and my personal Facebook page found at  http://www.facebook.com/VoicesOfTheSacredFeminine", "Sex, Religion, Power and Politics", "http://is2.mzstatic.com/image/thumb/Music71/v4/5f/d6/e3/5fd6e35d-3a39-39f4-44fe-b07b648e2328/source/600x600bb.jpg", "Spirituality"],
[ "Woodrow Wilson School of Public and International Affairs", "WooCast is a podcast series produced by Princeton University's Woodrow Wilson School of Public and International Affairs.", "WooCast: News & Politics from Princeton's Experts", "http://is5.mzstatic.com/image/thumb/Music71/v4/52/be/52/52be52da-140f-9230-bff5-04da05159581/source/600x600bb.jpg", "News & Politics"],
[ "Financial Times", "Discussion and analysis of U.K. and U.S. politics from the Financial Times' political commentators and correspondents. 

Sebastian Payne presents weekly episodes on Westminster matters. Demetri Sevastopulo and Courtney Weaver host the Washington instalments.", "FT Politics", "http://is2.mzstatic.com/image/thumb/Music71/v4/8d/bc/40/8dbc4086-3f04-335c-2d13-53dec8215aa4/source/600x600bb.jpg", "News & Politics"],
[ "theguardian.com", "Hosted by Guardian US reporter Sabrina Siddiqui, Politics for humans helps translate headline news into thoughtful, people-based conversations", "Politics for humans", "http://is1.mzstatic.com/image/thumb/Music62/v4/d7/e6/97/d7e697fb-c4c8-e680-70ed-40bac08b1867/source/600x600bb.jpg", "News & Politics"],
[ "Jamie Weinstein", "Opinion Journalist. TV Commentator. Author. Satirist. Tomato Lover.", "The Jamie Weinstein Show | Lessons from Leaders in Politics, Business & Media", "http://is1.mzstatic.com/image/thumb/Music71/v4/32/19/b3/3219b34b-5542-a7e5-4b42-472599772dc3/source/600x600bb.jpg", "News & Politics"],
[ "Amine Tais", "Historical surveys and current discussions surrounding religion, culture, and politics in Muslim settings", "The World of Islam: Culture, Religion, and Politics", "http://is5.mzstatic.com/image/thumb/Music/v4/25/44/97/25449781-ee1f-c5e1-36ae-525f18f5067f/source/600x600bb.jpg", "Islam"],
[ "F.A. Hayek Program for Advanced Study in Philosophy, Politics, and Economics", "The Hayek Program Podcast includes audio from lectures, interviews, and discussions of  scholars and visitors from the F. A. Hayek Program for Advanced Study in Philosophy, Politics, and Economics at the Mercatus Center at George Mason University. The F. A. Hayek Program is devoted to the promotion of teaching and research on the institutional arrangements that are suitable for the support of free and prosperous societies. Implicit in this statement is the presumption that those arrangements are to some extent open to conscious selection, as well as the appreciation that the type of arrangements that are selected within a society can influence significantly the economic, political, and moral character of that society.
", "Hayek Program Podcast", "http://is5.mzstatic.com/image/thumb/Music62/v4/b7/4d/64/b74d6430-1eb7-7b18-58f5-8ee672e826c0/source/600x600bb.jpg", "Higher Education"],
[ "New Hampshire Public Radio", "Brady Carlson hosts this run-down on the latest in Primary politics, including behind-the-scenes stories from reporters, tales and trends from the trail, and only in New Hampshire moments the rest of the country is missing out on. ", "Primarily Politics from New Hampshire Public Radio", "http://is2.mzstatic.com/image/thumb/Music62/v4/8b/3a/41/8b3a4138-a438-16c9-dae7-815a6a07cf9f/source/600x600bb.jpg", "News & Politics"],
[ "Drunken Politics", "Uncomfortably aggressive political talk.

Jamie Kilstein (Comedy Central, BBC) and Allison Kilkenny (Huffington Post, The Nation, Alternet.org, the BEAST) host a show about politics for people who hate politics! 

It's like CNN, but with much, much more swearing.", "Drunken Politics", "http://is5.mzstatic.com/image/thumb/Music62/v4/9c/e4/b6/9ce4b61e-a821-812e-5cce-1c3f05498127/source/600x600bb.jpg", "News & Politics"],
[ "The Institute of World Politics", "The Institute of World Politics is a graduate school of national security and international affairs, dedicated to developing leaders with a sound understanding of international realities and the ethical conduct of statecraft, based on knowledge and appreciation of the principles of the American political economy and the Western moral tradition.", "The Institute of World Politics", "http://is4.mzstatic.com/image/thumb/Music71/v4/8f/3e/56/8f3e5695-6cc3-707f-c0cd-63052ab1b670/source/600x600bb.jpg", "Higher Education"],
[ "Andrew & Henry: Millennials, Bloggers, and Patriots", "Love Being American is hosted by two millennials who discuss political and current events that are happening throughout America. Their unique perspective as millennials and avid patriots is guaranteed to entertain and give you a few laughs along the way.  

Each Sunday, Andrew and Henry, discuss political issues and current events that took place during the prior week.  

If you Love Being American, this podcast is for you. ", "Love Being American: Politics | Current Events | Patriotism | Millennials", "http://is4.mzstatic.com/image/thumb/Music62/v4/a0/af/ad/a0afad85-c6ac-c85b-2b96-435baf021c30/source/600x600bb.jpg", "News & Politics"],
[ "Loyal Books", "“Many who scoff at a book of etiquette would be shocked to hear the least expression of levity touching the Ten Commandments...” Thus opens the introduction to one of the most popular American non-fiction books – one that was avidly studied by both men and women, children and adults, leaders of society and those who yearned to be part of the charmed circle! 

Etiquette in Society, in Business, in Politics and at Home by Emily Post was first published in 1922 and became an instant bestseller. It has gone through several revisions, been updated frequently and continues to be an encyclopedia for those who are confused and in despair about which fork to use, and what to wear for a black tie dinner.

Following the success of her book, Emily Post attained cult status and became a byword for doing the right thing. She was syndicated in at least 200 journals and magazines and spoke extensively on radio programs meant to ease the pain of the socially inept. Today, her descendants head a multimillion dollar conglomerate which includes the Emily Post Institute. Almost all her grandchildren and great-great-grandchildren have something to do with giving advice on social matters.

The word etiquette has interesting origins. A Scottish gardener employed by Louis XIV to work in the gardens at Versailles was infuriated by people who trespassed on the perfectly manicured lawns. He put up signs or “tickets” known as “etiquettes” in French, warning people which paths to follow. However, when his signs were ignored, he complained to the King, who issued a stern warning, “Keep within the etiquettes!” 

The chapters in Etiquette are divided according to different titles. Starting with “Introductions” it advises the aspiring man or woman about town on what is the correct form to be followed while introducing people to each other. Other chapters include Consideration for Servants, Details of Place at a Formal Dinner, The Child at Table etc. Some of the rules may seem quaint, dated and even amusing today.

The rules have changed considerably since Emily Post first published her definitive book on the subject. Globalization has resulted in cross-cultural social dynamics. Yet, the primary rules of etiquette, namely respect, avoiding giving of offense and consideration for the feelings of others still remains paramount in our dealings and Etiquette in Society, in Business, in Politics and at Home remains a milestone in the annals of self-help books.
", "Etiquette in Society, in Business, in Politics and at Home by Emily Post", "http://is4.mzstatic.com/image/thumb/Music71/v4/c7/b4/e1/c7b4e1aa-1def-0271-a6c2-d1034585f5ec/source/600x600bb.jpg", "Self-Help"],
[ "Danny Winslow: Speculator of Politics | Primaries | 2016 Election Entertainment | Campaign News and Comedy", "Speculation on 2016 Presidential Election, the Primary Campaign Politics, Debates, Polls, News about Candidates like Hillary Clinton and Donald Trump with Total Coverage of Soundbite Comedy & Entertainment ", "Presidential Speculatainment", "http://is4.mzstatic.com/image/thumb/Music71/v4/07/3d/79/073d79cf-f161-6470-f621-82b022f441c7/source/600x600bb.jpg", "News & Politics"],
[ "Adam Camac and Daniel Laguros: Interviewers, Questioners, and Co-hosts", "The Wake Up Call Podcast is an interview-based audio program that features Adam Camac and Daniel Laguros interviewing experts on foreign relations, economics, history, current events, politics, political theory, and more.  The show has a special focus on, but is not limited to, libertarian and non-interventionist topics and viewpoints.", "Wake Up Call Podcast: Foreign Relations, Economics, Political Theory, Current Events, History, Politics, Countries, War and Pea", "http://is5.mzstatic.com/image/thumb/Music71/v4/8f/3e/05/8f3e05c5-f6de-8fb8-b90b-86d60c73f256/source/600x600bb.jpg", "News & Politics"],
[ "Reuters", "
            
                Reuters is your politics news source for up to the minute, impartial political news coverage on the leaders, policies and agendas that shape our world.     A SpokenEdition transforms written content into human-read audio you can listen to anywhere. It's perfect for times when you can't read - while driving, at the gym, doing chores, etc. Find more at www.spokenedition.com
            
        ", "Reuters Politics – Spoken Edition", "http://is2.mzstatic.com/image/thumb/Music62/v4/94/79/b6/9479b6c0-40b5-ad9f-a47e-814fcb443e54/source/600x600bb.jpg", "News & Politics"],
[ "BBC Radio 5 live", "John Pienaar shares his keen political observations, with news and interviews from key political figures in Westminster", "Pienaar's Politics", "http://is5.mzstatic.com/image/thumb/Music69/v4/0e/37/e7/0e37e7a2-6878-e0f9-9e04-a286ccfcbd04/source/600x600bb.jpg", "News & Politics"],
[ "BBC", "The BBC is a group of friends who like to get together and talk about beer, basketball, life, and other random stuff! Grab a beer and enjoy the show.  Check out our youtube page to view our recorded livestreams and all our episodes! 
Youtube: https://tinyurl.com/breakfastbeercrew
Instagram & Twitter: @breakfastbeercw
Itunes: https://tinyurl.com/BBCItunes", "Breakfast Beer Crew", "http://is1.mzstatic.com/image/thumb/Music62/v4/6d/0a/19/6d0a1941-5b6f-9a89-5eed-fd7520377b70/source/600x600bb.jpg", "Hobbies"],
[ "BBC World Service", "The day's top stories from BBC News compiled twice daily in the week, once at weekends.", "Global News Podcast", "http://is2.mzstatic.com/image/thumb/Music71/v4/b4/d3/d5/b4d3d5df-dfa7-b7c4-24a2-431510c284c1/source/600x600bb.jpg", "News & Politics"],
[ "BBC Radio 4", "Melvyn Bragg and guests discuss the history of ideas", "In Our Time", "http://is2.mzstatic.com/image/thumb/Music62/v4/64/60/65/646065f1-1260-3389-aeff-f83b7aa07a90/source/600x600bb.jpg", "History"],
[ "BBC World Service", "The best of BBC World Service documentaries and other factual programmes.", "The Documentary", "http://is5.mzstatic.com/image/thumb/Music62/v4/c9/16/c5/c916c5fe-f5d2-106a-3a36-aa1ff06513db/source/600x600bb.jpg", "History"],
[ "BBC Radio 4", "Download the best new comedy from Radio 4, every Friday. Features The News Quiz, The Now Show, Dead Ringers and The Museum of Curiosity.", "Friday Night Comedy from BBC Radio 4", "http://is3.mzstatic.com/image/thumb/Music71/v4/25/7b/c9/257bc9f5-b9b9-e771-361c-41dcef1ada70/source/600x600bb.jpg", "News & Politics"],
[ "BBC Radio 4", "Director of the British Museum, Neil MacGregor, narrates 100 programmes that retell humanity's history through the objects we have made", "A History of the World in 100 Objects", "http://is1.mzstatic.com/image/thumb/Music71/v4/3e/f1/ce/3ef1cef6-ab2d-3974-c028-5fd6d985b447/source/600x600bb.jpg", "History"],
[ "BBC Radio 4", "Insight, wit and analysis as BBC correspondents, journalists and writers take a closer look at the stories behind the headlines. Presented by Kate Adie and Pascale Harter.", "From Our Own Correspondent Podcast", "http://is2.mzstatic.com/image/thumb/Music71/v4/e9/3d/47/e93d4786-72b5-744d-2794-0e2fbe7d669c/source/600x600bb.jpg", "News & Politics"],
[ "BBC Radio 4", "Insight, analysis and expert debate as key policy makers are challenged on the latest news stories. From BBC Radio 4's Today programme", "Best of Today", "http://is2.mzstatic.com/image/thumb/Music71/v4/34/d5/02/34d502ec-1db4-7074-003e-6e013ea2188f/source/600x600bb.jpg", "News & Politics"],
[ "BBC World Service", "The story of our times told by the people who were there.", "Witness", "http://is4.mzstatic.com/image/thumb/Music69/v4/72/0e/67/720e6721-ca00-2478-62dd-a1469002b813/source/600x600bb.jpg", "History"],
[ "BBC Radio 4", "Witty, irreverent look at the world through scientists' eyes. With Brian Cox and Robin Ince", "The Infinite Monkey Cage", "http://is5.mzstatic.com/image/thumb/Music71/v4/6a/1c/d3/6a1cd36e-ee81-c95a-5ff5-f44959b9e9d7/source/600x600bb.jpg", "Science & Medicine"],
[ "BBC Radio 5 live", "Mark Kermode joins Simon Mayo to give his verdict on the week's movies", "Kermode and Mayo's Film Review", "http://is4.mzstatic.com/image/thumb/Music62/v4/35/eb/d5/35ebd53e-2389-9efe-07b1-4fdc94dc7e3f/source/600x600bb.jpg", "Society & Culture"],
[ "BBC World Service", "The daily drama of money and work from the BBC.", "Business Daily", "http://is4.mzstatic.com/image/thumb/Music62/v4/1c/e6/84/1ce68412-1074-d6e3-e123-9b259ef03963/source/600x600bb.jpg", "News & Politics"],
[ "BBC Radio 4", "Historical themes, events and key individuals from Akhenaten to Xenophon.", "In Our Time: History", "http://is2.mzstatic.com/image/thumb/Music71/v4/a0/ba/fe/a0bafe72-d792-7cbb-c9ca-06077984d88e/source/600x600bb.jpg", "History"],
[ "BBC World Service", "Explorations in the world of science.", "Discovery", "http://is3.mzstatic.com/image/thumb/Music62/v4/46/b8/56/46b85684-7bea-b0fa-6ba2-d52e317cd13c/source/600x600bb.jpg", "Science & Medicine"],
[ "BBC Radio", "Learn and practise useful English language for everyday situations with the BBC. Your weekly instruction manual for saying or doing something in English is published every Friday.", "6 Minute English", "http://is1.mzstatic.com/image/thumb/Music71/v4/5b/e4/72/5be472ad-24d4-70c0-6a58-5e9d5c9d9782/source/600x600bb.jpg", "Language Courses"],
[ "BBC World Service", "World Book Club invites the globe's great authors to discuss their best known novel. Presented by Harriett Gilbert, includes questions from World Service listeners.", "World Book Club", "http://is4.mzstatic.com/image/thumb/Music71/v4/da/8f/6d/da8f6d45-abe7-001e-71f6-f8b0f11a4fc5/source/600x600bb.jpg", "Personal Journals"],
[ "BBC Radio 4", "Desert Island Discs was created by Roy Plomley in 1942, and the format is simple: a guest is invited by Kirsty Young to choose the eight records they would take with them to a desert island", "Desert Island Discs", "http://is3.mzstatic.com/image/thumb/Music62/v4/28/75/9e/28759e1f-7e22-1cca-2e24-de2ff7dc7a08/source/600x600bb.jpg", "Personal Journals"],
[ "BBC World Service", "The latest business and finance news from around the world from the BBC", "World Business Report", "http://is1.mzstatic.com/image/thumb/Music62/v4/0f/56/28/0f562892-29f2-6710-def2-f30976f60b10/source/600x600bb.jpg", "Business News"],
[ "BBC World Service", "Technological and digital news from around the world.", "Click", "http://is3.mzstatic.com/image/thumb/Music71/v4/94/81/cd/9481cd3c-8a09-19a5-46e0-7042d7590363/source/600x600bb.jpg", "Science & Medicine"],
[ "BBC Radio 4", "Tim Harford and the More or Less team try to make sense of the statistics which surround us. From BBC Radio 4", "More or Less: Behind the Stats", "http://is2.mzstatic.com/image/thumb/Music62/v4/99/34/8a/99348a11-08d6-eff3-9ff9-93fe48fc9206/source/600x600bb.jpg", "News & Politics"],
[ "BBC Radio", "Every week, we look at a different everyday English phrase or piece of slang in this fun three-minute programme. From BBC World Service", "The English We Speak", "http://is3.mzstatic.com/image/thumb/Music62/v4/af/b4/71/afb47115-d451-04f3-3e0b-a42eafe31504/source/600x600bb.jpg", "Language Courses"],
[ "BBC Radio 3", "The best of BBC Radio 3's flagship arts and ideas programme Free Thinking - featuring in-depth interviews and debates with artists, scientists and public figures. ", "Arts and Ideas", "http://is1.mzstatic.com/image/thumb/Music71/v4/cb/68/b9/cb68b9f8-5150-2c59-d9fe-e1ab97761e64/source/600x600bb.jpg", "Places & Travel"],
[ "BBC Radio 4", "New research on how society works", "Thinking Allowed", "http://is5.mzstatic.com/image/thumb/Music71/v4/b5/07/21/b5072164-aa69-563f-ba60-aee186856922/source/600x600bb.jpg", "Science & Medicine"],
[ "BBC Radio 5 live", "The latest football news from BBC Radio 5 live with results, analysis, debate & exclusive interviews.", "5 live's Football Daily", "http://is3.mzstatic.com/image/thumb/Music62/v4/0f/f3/ab/0ff3ab8f-369e-508a-f12e-45136b19988b/source/600x600bb.jpg", "Professional"],
[ "BBC World Service", "The latest science research and news stories from all over the world.", "Science in Action", "http://is5.mzstatic.com/image/thumb/Music62/v4/c1/b8/51/c1b851aa-bb0a-f302-0aea-2468e7c9777a/source/600x600bb.jpg", "Technology"],
[ "BBC Radio Wales", "Religious affairs programme, tackling the thornier issues of the day in a thought-provoking manner", "All Things Considered", "http://is5.mzstatic.com/image/thumb/Music71/v4/80/0f/6b/800f6bd1-b92c-a9fe-94b0-285730267bb2/source/600x600bb.jpg", "Christianity"],
[ "BBC World Service", "Interviews, news and analysis of the day’s global events.", "Newshour", "http://is3.mzstatic.com/image/thumb/Music62/v4/91/95/c6/9195c636-4644-e0b6-dc48-89be7df86a56/source/600x600bb.jpg", "News & Politics"],
[ "BBC Radio 4", "From Altruism to Wittgenstein, philosophers, theories and key themes.", "In Our Time: Philosophy", "http://is2.mzstatic.com/image/thumb/Music71/v4/44/76/a5/4476a5ba-4e3c-044b-e69d-d7243aafcfc2/source/600x600bb.jpg", "History"],
[ "BBC Radio 4", "Biographical series in which guests choose someone who has inspired their lives.", "Great Lives", "http://is3.mzstatic.com/image/thumb/Music71/v4/54/7e/0c/547e0c24-862a-997b-063a-c69c0f0acdc3/source/600x600bb.jpg", "Personal Journals"],
[ "BBC World Service", "A daily digest of news and features presented by Dan Damon.", "World Update: Daily Commute", "http://is3.mzstatic.com/image/thumb/Music71/v4/20/44/5c/20445ce9-2d10-c3a3-a7ba-f4e88eb0d905/source/600x600bb.jpg", "News & Politics"],
[ "BBC Radio 5 live", "Have your say on the latest football action", "606", "http://is4.mzstatic.com/image/thumb/Music71/v4/44/5f/6b/445f6bce-fa4c-7d2b-8509-1ba0139c6529/source/600x600bb.jpg", "Professional"],
[ "BBC World Service", "News and analysis from the BBC's Focus on Africa. The Africa Today podcast is published from Monday to Friday. It contains the day's top African stories.", "Africa Today", "http://is3.mzstatic.com/image/thumb/Music71/v4/29/9b/37/299b3776-2331-57b6-da0f-be882a09ab0d/source/600x600bb.jpg", "News & Politics"],
[ "BBC Radio 4", "Weekly discussion programme, setting the cultural agenda every Monday", "Start the Week", "http://is5.mzstatic.com/image/thumb/Music71/v4/70/3d/a1/703da149-9317-3fb4-ed49-adcf7c4626b3/source/600x600bb.jpg", "Society & Culture"],
[ "BBC Radio 4", "Scientific principles, theory, and the role of key figures in the advancement of science.", "In Our Time: Science", "http://is2.mzstatic.com/image/thumb/Music71/v4/e1/e6/d0/e1e6d06a-e75c-d9d5-5b1f-2fdc74fc2189/source/600x600bb.jpg", "History"],
[ "BBC Radio", "Insights into the business world - featuring content from BBC Radio 4's In Business programme, and also Global Business from the BBC World Service.", "The World of Business", "http://is5.mzstatic.com/image/thumb/Music71/v4/9f/00/57/9f005750-f4a8-8f13-f49a-37df470ebe97/source/600x600bb.jpg", "Business News"],
[ "BBC Radio 4", "Contemporary drama in a rural setting", "The Archers", "http://is3.mzstatic.com/image/thumb/Music19/v4/35/65/c1/3565c18c-4036-e486-8e73-d92d99fd38e0/source/600x600bb.jpg", "Performing Arts"],
[ "BBC Radio 4", "Brighten your week with the latest BBC Radio 4 comedy. Comedians including Mark Thomas and Tom Wrigglesworth alongside classic shows such as Just A Minute and Ed Reardon.", "Comedy of the Week", "http://is1.mzstatic.com/image/thumb/Music71/v4/27/e3/aa/27e3aac1-f24b-3b9e-3376-25baacc30a28/source/600x600bb.jpg", "Comedy"],
[ "BBC Radio 4", "A rich selection of documentaries aimed at relentlessly curious minds, introduced by Rhianna Dhillon.", "Seriously...", "http://is1.mzstatic.com/image/thumb/Music71/v4/8e/ae/6c/8eae6c1e-7cc5-def4-1950-870ed4fb5da7/source/600x600bb.jpg", "News & Politics"],
[ "BBC Radio 4", "Every Friday we bring you a new drama from BBC Radio 4 or Radio 3. Exercise your imagination with some of the best writers and actors on radio. Storytelling at its very best.", "Drama of the Week", "http://is3.mzstatic.com/image/thumb/Music71/v4/98/36/5d/98365d6a-d3e5-cdbe-fd21-d268df97b303/source/600x600bb.jpg", "Performing Arts"],
[ "BBC Radio 4", "Live magazine programme on the worlds of arts, literature, film, media and music", "Front Row", "http://is1.mzstatic.com/image/thumb/Music71/v4/ad/db/6b/addb6be5-3a46-10d1-aa0a-74def98bdd00/source/600x600bb.jpg", "Society & Culture"],
[ "BBC Radio 1", "All of Scott’s show, without the music! Innuendo Bingo, prank calls, Chris’s stories, listeners’ dilemmas, Real Or No Real, stupid games: it’s all here for you, five days a week.", "Scott Mills Daily", "http://is4.mzstatic.com/image/thumb/Music62/v4/a4/12/f5/a412f5c1-94fe-4838-fe0a-d32dc9e0ab44/source/600x600bb.jpg", "Comedy"],
[ "BBC Radio 4", "Popular culture, poetry, music and visual arts and the roles they play in our society.", "In Our Time: Culture", "http://is1.mzstatic.com/image/thumb/Music62/v4/ae/51/de/ae51de35-78b6-2108-e605-71234b013b5c/source/600x600bb.jpg", "History"],
[ "BBC Radio 5 live", "Formula 1 interviews, reaction and reports. 5 live presents a round-up of the race weekend.", "Chequered Flag Formula 1", "http://is2.mzstatic.com/image/thumb/Music62/v4/fd/27/87/fd278768-ef3e-39ff-ed51-b7c8cf7b910d/source/600x600bb.jpg", "Professional"],
[ "BBC Radio 5 live", "5 live's science podcast, featuring Dr Karl, plus Dr Chris and Naked Scientists Chris Smith and Kat Arney with the hottest science news stories and analysis.", "5 live Science Podcast", "http://is1.mzstatic.com/image/thumb/Music62/v4/ee/9c/a9/ee9ca9ef-9863-9da1-288d-19a6698d383c/source/600x600bb.jpg", "Natural Sciences"],
[ "BBC Radio 4", "The programme that offers a female perspective on the world", "Woman's Hour", "http://is5.mzstatic.com/image/thumb/Music71/v4/c2/df/a0/c2dfa03e-a69f-4db3-51bc-b2c20c2e4dfd/source/600x600bb.jpg", "News & Politics"],
[ "BBC Radio 4", "Programme examining the ideas and forces which shape public policy in Britain and abroad, presented by distinguished writers, journalists and academics", "Analysis", "http://is1.mzstatic.com/image/thumb/Music71/v4/59/bd/ba/59bdba79-0d6f-f4dd-0658-a504f0d2d283/source/600x600bb.jpg", "News & Politics"],
[ "BBC Radio 2", "Catch up with the latest Breakfast fun with Chris Evans. Hear the best stories and the biggest guests, every week. From BBC Radio 2.", "Chris Evans - The Best Bits", "http://is1.mzstatic.com/image/thumb/Music62/v4/77/6b/85/776b8552-d3fc-3027-ae29-6cd6e6ee0993/source/600x600bb.jpg", "Comedy"],
[ "BBC Radio 4", "Investigating every aspect of the food we eat", "Food Programme", "http://is4.mzstatic.com/image/thumb/Music71/v4/90/6c/29/906c291c-70fa-9a3c-a5c8-39e945a8f5eb/source/600x600bb.jpg", "Food"],
[ "BBC Radio 4", "The BBC Natural History Unit produces a wide range of programmes that aim to immerse a listener in the wonder, surprise and importance that nature has to offer.", "Best of Natural History Radio", "http://is3.mzstatic.com/image/thumb/Music62/v4/93/89/14/938914a8-f895-6bd3-3d83-717139ff02ca/source/600x600bb.jpg", "Natural Sciences"],
[ "BBC Radio 4", "This podcast features Open Book and A Good Read. In Open Book Mariella Frostrup talks to authors about their work. In A Good Read Harriett Gilbert discusses favourite books.", "Books and Authors", "http://is3.mzstatic.com/image/thumb/Music62/v4/d3/1c/86/d31c866b-bc96-df7f-fc03-b31c49e33454/source/600x600bb.jpg", "Society & Culture"],
[ "Vox / Panoply / Ezra Klein / Sarah Kliff / Matt Yglesias", "Everyone is always warning you not to get lost in the weeds. But not Vox's Ezra Klein, Sarah Kliff, and Matthew Yglesias. They love the weeds. That's where all the policy is. This is the podcast for people who follow politics because they love thinking about health care, economics, and zoning. It is not a podcast for people who like hearing talk about gaffes.", "Vox's The Weeds", "http://is2.mzstatic.com/image/thumb/Music122/v4/e5/07/b8/e507b82d-6d5d-57cd-b3a9-ed4aba0edd32/source/600x600bb.jpg", "News & Politics"],
[ "Vox / Panoply", "Ezra Klein gives you a chance to get inside the heads of the newsmakers and power players in politics and media. These are extended conversations with policymakers, writers, technologists, and business leaders about what they believe in and why. Look elsewhere for posturing confrontation and quick reactions to the day's news. Subscribe for the anti-soundbite.", "The Ezra Klein Show", "http://is4.mzstatic.com/image/thumb/Music122/v4/3f/81/19/3f811910-86c3-63c3-1912-bf461343f229/source/600x600bb.jpg", "News & Politics"],
]
end