module SampleProviders
PROVIDERS = [
'Politics',
'Politics',
'NPR',
'FiveThirtyEight - Nate Silver, Jody Avirgan, Clare Malone, Harry Enten',
'WNYC Studios and The New Yorker',
'HuffPost Politics',
'Bruce Carlson',
'TEDTalks',
'The Weekly Standard',
'Julie & Brandy',
'Capitol Steps',
'KCRW.com',
'Pantsuit Politics',
'Randy Newberg: Hunter, Host of Fresh Tracks TV, Speaker, and Hunting Activist',
'Michael Baranowski and Jay Carson',
'theguardian.com',
'ABC News',
'Justin Robert Young',
'Slate Magazine/Panoply',
'Marketplace',
'Bloomberg News',
'Steve Patterson | Covering Philosophy, Religion, Politics, Economics, Science, Mathematics, Metaphysics, Epistemology, Logic, Truth, Christianity, Buddhism, Hinduism, Atheism, Spirituality, Language, and Cultural Criticism',
'Shorenstein Center on Media, Politics and Public Policy at Harvard Kennedy School',
'Slate',
'WAMU 88.5',
'Letters and Politics',
'David Runciman and Catherine Carr',
'The Huffington Post',
'PodcastOne',
'Courtney Brown, Ph.D.',
'John Myers',
'Oregon Public Broadcasting',
'Karen Tate',
'Woodrow Wilson School of Public and International Affairs',
'Financial Times',
'theguardian.com',
'Dr. David Naimon',
'Joe Ferrantelli, D.C.',
'Jamie Weinstein',
'Amine Tais',
'F.A. Hayek Program for Advanced Study in Philosophy, Politics, and Economics',
'New Hampshire Public Radio',
'Drunken Politics',
'The Institute of World Politics',
'Andrew & Henry: Millennials, Bloggers, and Patriots',
'Loyal Books',
'Danny Winslow: Speculator of Politics | Primaries | 2016 Election Entertainment | Campaign News and Comedy',
'Adam Camac and Daniel Laguros: Interviewers, Questioners, and Co-hosts',
'Reuters',
'BBC Radio 5 live',
'BBC',
'BBC World Service',
'BBC Radio 4',
'BBC World Service',
'BBC Radio 4',
'BBC Radio 4',
'BBC Radio 4',
'BBC Radio 4',
'BBC World Service',
'BBC Radio 4',
'BBC Radio 5 live',
'BBC World Service',
'BBC Radio 4',
'BBC World Service',
'BBC Radio',
'BBC World Service',
'BBC Radio 4',
'BBC World Service',
'BBC World Service',
'BBC Radio 4',
'BBC Radio',
'BBC Radio 3',
'BBC Radio 4',
'BBC Radio 5 live',
'BBC World Service',
'BBC Radio Wales',
'BBC World Service',
'BBC Radio 4',
'BBC Radio 4',
'BBC World Service',
'BBC Radio 5 live',
'BBC World Service',
'BBC Radio 4',
'BBC Radio 4',
'BBC Radio',
'BBC Radio 4',
'BBC Radio 4',
'BBC Radio 4',
'BBC Radio 4',
'BBC Radio 4',
'BBC Radio 1',
'BBC Radio 4',
'BBC Radio 5 live',
'BBC Radio 5 live',
'BBC Radio 4',
'BBC Radio 4',
'BBC Radio 2',
'BBC Radio 4',
'BBC Radio 4',
'BBC Radio 4',
'Vox / Panoply / Ezra Klein / Sarah Kliff / Matt Yglesias',
'Vox / Panoply',
]
end